apiVersion: v1
kind: BuildConfig
metadata:
  name: springlab1
spec:
  source:
    type: Binary
    binary: {  }
    secrets: null
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: tools
        name: 'java-jboss-openjdk8-jdk:latest'
  output:
    to:
      kind: ImageStreamTag
      name: 'springlab1:latest'
