kind: ConfigMap
apiVersion: v1
metadata:
  name: fake-balances
data:
  application.yml: |
   spring:
     jmx:
       enabled: true
   management:
     port: 9001
     security:
       enabled: false
