apiVersion: v1
kind: BuildConfig
metadata:
  name: fake-balances-service-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.sebank.se/s66214/fake-balances.git'
      ref: master
    sourceSecret:
     name: github-sebank-se
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
