apiVersion: v1
kind: BuildConfig
metadata:
  name: springlab1-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/jober64/springlab1.git'
      ref: master
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
